### ISSUE TITLE
error: grid is not defined

### ISSUE THREAD

**Issue by mikeny07** [indiana-dev/WebGPU-Fluid-Simulation#1]
tried to change 'rdx' or 'dyeRdx' parameter from GUI, but got the following error message:

--------------------------------------------------------------------
init.js:136 Uncaught ReferenceError: grid is not defined
    at t.__onChange (init.js:136:9)
    at t.value (dat.gui.min.js:13:16995)
    at t.value (dat.gui.min.js:13:23215)
    at t.setValue (dat.gui.min.js:13:9877)
    at HTMLInputElement.<anonymous> (dat.gui.min.js:13:24016)
    at HTMLInputElement.<anonymous> (dat.gui.min.js:13:24270)
-------------------------------------------------------------------------------

the code snippet at init.js 136 is:

grid.update(device.queue, [settings.grid_w, settings.grid_h, settings.dye_w, settings.dye_h, settings.dx, settings.rdx, settings.dyeRdx])

it seems that the grid instance needs to be recreated when changing rdx or dyeRdx

**Comment by indiana-dev** [comment]
My first issue, I'm excited!
These two parameters were more for testing purposes and I forgot to remove them. 
I fixed the issue and only kept the `rdx` parameter as `dyeRdx` was less relevant.

Thanks for pointing this out!
